version: '3.9'

volumes:
  lvr-ambsdr-be:
    driver: local
    driver_opts:
      type: none
      device: /home/chandra/CodeBase/Laravel/micro-service/laravel-ambassador/ #change me (needs full path)
      o: bind

  lvr-ambsdr-db:
    driver: local
    driver_opts:
      type: none
      device: /home/chandra/CodeBase/Laravel/micro-service/laravel-ambassador/storage/dbdata #change me (needs full path)
      o: bind

services:
  backend:
    build: .
    ports:
      - 8000:8000
    volumes:
      - lvr-ambsdr-be:/app:Z
    command: 'php artisan serve --host=0.0.0.0'
    depends_on:
      - db
    networks:
      - default
      - lvr-users

  db:
    image: mysql:8.0.28
    restart: always
    environment:
      MYSQL_DATABASE: ambassador
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
    volumes:
      - lvr-ambsdr-db:/var/lib/mysql:Z
    ports:
      - 33066:3306
    networks:
      - default

#  redis:
#    image: redis:6
#    ports:
#      - 6379:6379
#    networks:
#      - default

networks:
  lvr-users:
    external:
      name: lvr-users

  default:
    name: lvr-ambassador

